
POST http://localhost:4000/getInfoBook
Content-Type:application/json

{
    "bookID" : "60adba1fddf0a1076cb832a3"
}

###
POST http://localhost:4000/rentBook
Content-Type:application/json

{
    "email": "square.741246@sis.hust.edu.vn",
    "listIDBook": ["60adba1fddf0a1076cb832a3", "60adba1fddf0a1076cb832a3"]
}


###
POST  http://localhost:4000/getInfoBook
Content-Type:application/json

{
    "bookID": "608e5a5e0ec4fa1b7848055e"
}


###
POST http://localhost:4000/retreiveBook
Content-Type:application/json

{
    "bookId": "608e5a410ec4fa1b784803f2",
    "userId" : "60a4af2a2186d82c045122a8"
}

###
GET http://localhost:4000/getDataRegister

###
GET http://localhost:4000/getBookRent
Content-Type:application/json

###
POST  http://localhost:4000/getInfoBook
Content-Type:application/json

{
    "bookID": "608e5a5e0ec4fa1b7848055e"
}

###

POST http://localhost:4000/exportBook
Content-Type:application/json

{
    "bookId" : "60ae309b57b81006d463b61d"
}

###
GET http://locahost:4000/remove



