GET http://localhost:4000/getListAllBooks 

### 
GET http://localhost:4000/getListAllBooksElement

###

POST http://localhost:4000/importBook 
Content-Type:application/json

{
    "title" : "Triết học",
    "author": "Vũ Khắc Chinh",
    "genre": "Đại cương",
    "amount": "500",
    "code" : "TRH"
}

###

POST http://localhost:4000/exportBook
Content-Type:application/json

{
    "code" : "TMQ123",
    "listBookExport" : [
        {
            "id": "6087901d9bceb83368f18120"
        },
        {
            "id": "6087901d9bceb83368f1811f"
        }
    ]
}

###
GET http://localhost:4000/borrowingBooks/6096d4a9e8439a1bc0165a28/1
Content-Type:application/json

###
GET http://localhost:4000/getBookInfor/6086e3ed260fe01114f2431d
Content-Type:application/json
###
GET http://localhost:4000/searchBook?&author=Kiên&page=0&title=
