GET http://localhost:4000/getListAllBooks 

### 
GET http://localhost:4000/getListAllBooksElement

###

POST http://localhost:4000/importBook 
Content-Type:application/json

{
    "title" : "tin hoc dai cuong",
    "id" : "THDC",
    "author": "Tran Dinh Truong",
    "genre": "dai cuong",
    "amount": "5",
    "code" : "TMQ123"
}

###

POST http://localhost:4000/exportBook
Content-Type:application/json

{
    "code" : "TMQ123",
    "listBookExport" : [
        {
            "id": "6087901d9bceb83368f18120"
        },
        {
            "id": "6087901d9bceb83368f1811f"
        }
    ]
}

###

