GET http://localhost:4000/getListAllBooks 

### 
GET http://localhost:4000/getListAllBooksElement

###

POST http://localhost:4000/importBook 
Content-Type:application/json

{
    "title" : "tin hoc dai cuong",
    "id" : "THDC",
    "author": "Tran Dinh Truong",
    "genre": "dai cuong",
    "amount": "5"
}