
POST http://localhost:4000/getInfoBook
Content-Type:application/json

{
    "bookID" : "6086e3ed260fe01114f2431"
}

###
POST http://localhost:4000/rentBook
Content-Type:application/json

{
    "email": "thanh.la170115@sis.hust.edu.vn",
    "listIDBook": ["60a5a7889c33ba17b4613315"]
}