POST http://localhost:4000/apiUser/login
Content-Type:application/json

{
    "email" : "aloha.669124@sis.hust.edu.vn",
    "password" : "87654321"
}
###

GET http://localhost:4000/apiUser/getListAllUsers
Content-Type:application/json
###

POST http://localhost:4000/apiUser/createNewUser
Content-Type:application/json

{
    "email": "ngaikien@xxx.com",
    "password": "12345678",
    "confirmPassword" : "12345678",
    "firstName": "TV",
    "lastName": "Kiên",
    "birthday": "10-01-2008",
    "class": "CNTT-xx"
}

###
GET http://localhost:4000/apiUser/getInformation/thanh.la170115@sis.hust.edu.vn
###


PUT  http://localhost:4000/apiUser/changePassword/aloha.669124@sis.hust.edu.vn
Content-Type:application/json

{   
    "oldPassword" : "12345678",
    "newPassword": "20173429",
    "confirmNewPassword" : "20173429"
}

###

DELETE  http://localhost:4000/apiUser/deleteByEmail/thanh.la170115@sis.hust.edu.

